/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedFundacionRouteImport } from './routes/_authenticated/fundacion'
import { Route as AuthenticatedExplorarRouteImport } from './routes/_authenticated/explorar'
import { Route as AuthenticatedEmpresaRouteImport } from './routes/_authenticated/empresa'

const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFundacionRoute = AuthenticatedFundacionRouteImport.update({
  id: '/fundacion',
  path: '/fundacion',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExplorarRoute = AuthenticatedExplorarRouteImport.update({
  id: '/explorar',
  path: '/explorar',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmpresaRoute = AuthenticatedEmpresaRouteImport.update({
  id: '/empresa',
  path: '/empresa',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/fundacion': typeof AuthenticatedFundacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/empresa': typeof AuthenticatedEmpresaRoute
  '/explorar': typeof AuthenticatedExplorarRoute
  '/fundacion': typeof AuthenticatedFundacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/registro': typeof RegistroRoute
  '/_authenticated/empresa': typeof AuthenticatedEmpresaRoute
  '/_authenticated/explorar': typeof AuthenticatedExplorarRoute
  '/_authenticated/fundacion': typeof AuthenticatedFundacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/registro'
    | '/empresa'
    | '/explorar'
    | '/fundacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/registro' | '/empresa' | '/explorar' | '/fundacion'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/registro'
    | '/_authenticated/empresa'
    | '/_authenticated/explorar'
    | '/_authenticated/fundacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegistroRoute: typeof RegistroRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/fundacion': {
      id: '/_authenticated/fundacion'
      path: '/fundacion'
      fullPath: '/fundacion'
      preLoaderRoute: typeof AuthenticatedFundacionRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/explorar': {
      id: '/_authenticated/explorar'
      path: '/explorar'
      fullPath: '/explorar'
      preLoaderRoute: typeof AuthenticatedExplorarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/empresa': {
      id: '/_authenticated/empresa'
      path: '/empresa'
      fullPath: '/empresa'
      preLoaderRoute: typeof AuthenticatedEmpresaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedEmpresaRoute: typeof AuthenticatedEmpresaRoute
  AuthenticatedExplorarRoute: typeof AuthenticatedExplorarRoute
  AuthenticatedFundacionRoute: typeof AuthenticatedFundacionRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEmpresaRoute: AuthenticatedEmpresaRoute,
  AuthenticatedExplorarRoute: AuthenticatedExplorarRoute,
  AuthenticatedFundacionRoute: AuthenticatedFundacionRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegistroRoute: RegistroRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
